imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: v1
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType        
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#Sonata User Configuration
sonata_user:
    security_acl: false
    manager_type: orm # can be orm or mongodb
    class:
        user: Application\Sonata\UserBundle\Entity\User
        group: Application\Sonata\UserBundle\Entity\Group

#Sonata Block Configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)    
        sonata.admin.block.admin_list:
            contexts:   [admin]

#Sonata Admin UI Configuration
sonata_admin:
    title:       Nexus Admin
    #title_logo: bundles/acmedemo/img/fancy_acme_logo.png
    security: 
        handler: sonata.admin.security.handler.role  

#FriendOfSymphony User Configuration
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User

    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm

    service:
        user_manager: sonata.user.orm.user_manager                      # If you're using doctrine orm

#MopaBootstrap Configuration
mopa_bootstrap:
    form:
        render_fieldset: false
        show_legend: false
        horizontal_label_class: ~
        horizontal_input_wrapper_class: ~        
    menu: ~  # enables twig helpers for menu

#JMS I18N Routing
services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

jms_i18n_routing:
    default_locale: en
    locales: %locale_available%
    strategy: prefix_except_default

jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%]
            output_dir: %kernel.root_dir%/Resources/translations
            excluded_names: [*TestCase.php, *Test.php]
            excluded_dirs: [cache, data, logs]
            extractors: [jms_i18n_routing]
        core:
            dirs: [%kernel.root_dir%/../src/Nexus/CoreBundle]
            output_dir: %kernel.root_dir%/../src/Nexus/CoreBundle/Resources/translations
            excluded_names: [*TestCase.php, *Test.php]
            excluded_dirs: [cache, data, logs]
            extractors: [jms_i18n_routing]
            keep: yes            
        admin:
            dirs: [%kernel.root_dir%/../src/Nexus/AdminBundle]
            output_dir: %kernel.root_dir%/../src/Nexus/AdminBundle/Resources/translations
            ignored_domains: [SonataAdminBundle]
            excluded_names: [*TestCase.php, *Test.php]
            excluded_dirs: [cache, data, logs]
            extractors: [jms_i18n_routing]
            keep: yes
