nexus_core_homepage:
    pattern:  /
    defaults: { _controller: NexusCoreBundle:Core:index }

nexus_api_fight:
    pattern:  /api/fight
    defaults: { _controller: NexusCoreBundle:API:fight }
    options:
        expose: true