nexus_core_homepage:
    pattern:  /
    defaults: { _controller: NexusCoreBundle:Core:index }

nexus_api_fight:
    pattern:  /api/fight
    defaults: { _controller: NexusCoreBundle:API:fight }
    options:
        expose: true

nexus_api_event_log:
    pattern:  /api/event
    defaults: { _controller: NexusCoreBundle:API:event }
    options:
        expose: true

nexus_api_leaderboard:
    pattern:  /api/leaderboard
    defaults: { _controller: NexusCoreBundle:API:leaderboard }
    options:
        expose: true