parameters:
#    nexus_core.example.class: Nexus\CoreBundle\Example

services:
#    nexus_core.example:
#        class: %nexus_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
