parameters:
#    nexus_core.example.class: Nexus\CoreBundle\Example

services:
    nexus_core.fight_manager:
        class: Nexus\CoreBundle\Services\FightManager
        arguments: [@doctrine.orm.entity_manager, @security.context, @nexus_core.fight_logger]
    nexus_core.fight_logger:
        class: Nexus\CoreBundle\Services\FightLogger
        arguments: [@doctrine.orm.entity_manager]
#    nexus_core.example:
#        class: %nexus_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
