services:
    sonata.admin.character:
        class: Nexus\AdminBundle\Admin\CharacterAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Nexus", label: "Characters" }
        arguments:
            - ~
            - Nexus\CoreBundle\Entity\Characters
            - ~
        calls:
            - [ setTranslationDomain, [SonataCustomAdmin]]
            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
    sonata.admin.weekly_update:
        class: Nexus\AdminBundle\Admin\WeeklyUpdateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Nexus", label: "Weekly Updates" }
        arguments:
            - ~
            - Nexus\CoreBundle\Entity\WeeklyUpdate
            - "NexusAdminBundle:WeeklyUpdateAdmin"
        calls:
            - [ setTranslationDomain, [SonataCustomAdmin]]
            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
    sonata.admin.monster:
        class: Nexus\AdminBundle\Admin\MonsterAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Nexus", label: "Monsters" }
        arguments:
            - ~
            - Nexus\CoreBundle\Entity\Monster
            - ~
        calls:
            - [ setTranslationDomain, [SonataCustomAdmin]]
            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
    sonata.admin.fight:
        class: Nexus\AdminBundle\Admin\FightAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Nexus", label: "Fights" }
        arguments:
            - ~
            - Nexus\CoreBundle\Entity\Fight
            - ~
        calls:
            - [ setTranslationDomain, [SonataCustomAdmin]]
            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
    # sonata.admin.experience:
    #     class: Nexus\AdminBundle\Admin\ExperienceAdmin
    #     tags:
    #         - { name: sonata.admin, manager_type: orm, group: "Nexus", label: "Experience Chart" }
    #     arguments:
    #         - ~
    #         - Nexus\CoreBundle\Entity\ExperienceChart
    #         - ~
    #     calls:
    #         - [ setTranslationDomain, [SonataCustomAdmin]]
    #         - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]