parameters:
#    nexus_admin.example.class: Nexus\AdminBundle\Example

services:
#    nexus_admin.example:
#        class: %nexus_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
