parameters:
#    nexus_admin.example.class: Nexus\AdminBundle\Example

services:
    nexus_core.update_manager:
        class: Nexus\AdminBundle\Services\UpdateManager
        arguments: [@doctrine.orm.entity_manager, @validator]
