<?php

namespace Nexus\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WeeklyUpdateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeeklyUpdateRepository extends EntityRepository
{
}
