_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

_lynkware:
    pattern: /lynkware
    defaults: { _controller: AcmeDemoBundle:Lynkware:index }

_lynkware-fa:
    pattern: /lynkware-fa
    defaults: { _controller: AcmeDemoBundle:Lynkware:fontAwesome }